# -*- coding: utf-8 -*-
"""passwordchecker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoHtWEmcpk2FLJp9fiCoJWu3k5MvJXVz
"""

import re

def password_strength_checker(password):
    strength = {
        'Length': len(password) >= 8,
        'Lowercase': bool(re.search(r'[a-z]', password)),
        'Uppercase': bool(re.search(r'[A-Z]', password)),
        'Digits': bool(re.search(r'\d', password)),
        'Special Characters': bool(re.search(r'[!@#$%^&*(),.?":{}|<>]', password)),
        'Uniqueness': len(set(password)) >= 5
    }

    score = sum(strength.values())
    feedback = ""

    if score == 6:
        feedback = "Strong password"
    elif score >= 4:
        feedback = "Moderate password, consider adding more complexity"
    else:
        feedback = "Weak password, improve length, add different types of characters"

    print("Password Strength Analysis:")
    for factor, passed in strength.items():
        status = "Passed" if passed else "Failed"
        print(f"{factor}: {status}")

    print(f"Overall Feedback: {feedback}")

# Example usage
password = input("Enter a password to check its strength: ")
password_strength_checker(password)